### ISSUE TITLE
API Keyとかベタ書きなの大丈夫だろうか

### ISSUE THREAD

**Issue by take4** [manimoto881985/moyatasu_js#1]
- 環境変数化してビルド時だけ使うようにする？
- 無料でプライベートリポジトリが作れるところ、gitlabかbitbucket？に移行もありかもしれない

**Comment by manimoto881985** [comment]
これ自分も心配で確認したんだけど大丈夫らしい 😄 
https://medium.com/@dyoshikawa/d602ef5b5d2c

**Comment by manimoto881985** [comment]
gitlab移行はありだね！
