### ISSUE TITLE
コメント機能

### ISSUE THREAD

**Issue by take4** [manimoto881985/moyatasu_js#2]

**Comment by satour** [comment]
どういうインターフェース&インタラクションにするか吟味必要やね

・別画面に切り替わる
・画面切り替えなく、expand&collapseな感じにする
・モーダルにする
・etc

**Comment by manimoto881985** [comment]
@satour おお！実装後にコメント付いてたのに気づいた… 💦 
とりあえず「画面切り替えなく、expand&collapseな感じにする」で作ってしまった。。

コメントが長くなることが多い場合だとモーダルにしたりのほうがよかったりかもね。

**Comment by manimoto881985** [comment]
とりあえずコメント機能の実装はしたのでこのissueはクローズしますー
インターフェース&インタラクションを変える場合はまた別issueでやりましょうー
