### ISSUE TITLE
投稿が増えてきたことによる、ページ表示速度低下への対処方法

### ISSUE THREAD

**Issue by satour** [manimoto881985/moyatasu_js#21]
# パッと思いついた候補
- ページネーション
- 都度追加取得（名前ある？）
  - 「もっと読む...」みたいなボタンをフィードの最下部に設置し、クリック/タップ にて任意の件数(10件とか)の投稿を追加取得
  - 上記の亜流で、ブラウザのフォーカスがフィードの最下部にあたったら、任意の件数の投稿を追加取得
  - etc

**Comment by satour** [comment]
## pagenation

## read more...
![read more](https://i.gyazo.com/66cd50fe2e9a6a381b283bb52c12558c.png)

**Comment by taiSon** [comment]
呼び方は無限スクロール ( infinite scroll ) とかなんとか。
モヤタスは UI がモバイルファーストなんで無限スクロールのほうがいいかな？

**Comment by satour** [comment]
これもう解消したからイシュー閉じちゃお
